# ============================================================
# Import necessary libraries
# ============================================================
import gurobipy as gp
from gurobipy import GRB
import math

from utils.validation import input_validation
# Import global parameters
from config import LINK_COST, RELIABILITY_BY_NODE_TYPE

# ============================================================
# Main function: hybrid_model
# ============================================================


def hybrid_model(baseModel, totalNodes, requiredReliability):
    """
    Extends the base model to include constraints and costs for the hybrid model.

    Parameters:
    - baseModel (gurobipy.Model): Base model generated by base_model.
    - totalNodes (int): Number of nodes in the network (minimum 4).
    - requiredReliability (float): Total required reliability (0 < value < 1).

    Returns:
    - total_cost (float): Total cost of the solution.
    - decision_variables (dict): Decision variables and their values.
    - model (gurobipy.Model): Optimized model.
    """
    # Input validation
    input_validation(totalNodes, LINK_COST, RELIABILITY_BY_NODE_TYPE)

    # Copy of the base model
    model = baseModel.copy()

    nodeSet = range(totalNodes)
    subnetSet = range(totalNodes // 3 + 1)
    nodesTypeSet = range(len(RELIABILITY_BY_NODE_TYPE))

    # Recover the linksCost variable from the base model
    linksCost = model.getVarByName("linksCost")
    if linksCost is None:
        raise ValueError(
            "linksCost variable not found in the base model.")

    # Recover decision variables x[u, i]
    x = {
        tuple(map(int, var.varName.split('[')[1].split(']')[0].split(','))): var
        for var in model.getVars() if "x" in var.varName
    }

    # Remove general linksCost constraint (if it exists)
    linksCost_Condition = model.getConstrByName("LinksCost_General")
    if linksCost_Condition:
        model.remove(linksCost_Condition)

    # Additional variables
    y = model.addVars(nodeSet, subnetSet, vtype=GRB.BINARY, name="y")
    activeSubnet = model.addVars(subnetSet, vtype=GRB.BINARY, name="activeSubnet")
    nodesBySubnet = model.addVars(subnetSet, vtype=GRB.INTEGER, name="nodesBySubnet")
    meshSubnetLinks = model.addVars(subnetSet, vtype=GRB.INTEGER, name="meshSubnetLinks")

    # Auxiliary definitions
    model.addConstrs(  # Definition of nodes per subnet
        (nodesBySubnet[j] == gp.quicksum(y[u, j] for u in nodeSet) for j in subnetSet),
        name="meshNodesBySubnet_def"
    )
    model.addConstrs(  # Definition of mesh links per subnet j > 0
        (2 * meshSubnetLinks[j] == nodesBySubnet[j] * (nodesBySubnet[j] - 1) for j in subnetSet if j > 0),
        name="Mesh_Links_Subnet"
    )
    model.addConstr( # Definition of mesh links per subnet j = 0
        meshSubnetLinks[0] == 0,
        name="Mesh_Links_Series_Subnet"
    )

    # Constraints
    model.addConstrs( # Each node belongs to a single subnet
        (gp.quicksum(y[u, j] for j in subnetSet) == 1 for u in nodeSet),
        name="Subnet_Uniqueness"
    )
    model.addConstr( # At least one active subnet
        gp.quicksum(activeSubnet[j] for j in subnetSet) >= 1,
        name="AtLeastTwoActiveSubnets"
    )
    model.addConstrs( # Active mesh subnets must have at least 3 nodes
        (nodesBySubnet[j] >= 3 * activeSubnet[j] for j in subnetSet if j > 0),
        name="Subnets_Min_3"
    )
    model.addConstr( # Sum of nodes assigned to active subnets must equal total nodes
        (gp.quicksum(activeSubnet[j]*nodesBySubnet[j] for j in subnetSet) == totalNodes),
        name="Total_Assigned_Nodes"
    )

    # Link cost calculation
    extraSubnetConnections = gp.quicksum(activeSubnet[j] for j in subnetSet if j > 0) - 1
    totalMeshSubnetLinks = gp.quicksum(meshSubnetLinks[j] for j in subnetSet if j > 0)
    model.addConstr(
        linksCost == LINK_COST * (nodesBySubnet[0] + extraSubnetConnections + totalMeshSubnetLinks),
        name="LinksCost_Hybrid"
    )

    ############################ RELIABILITY ############################

    nodeReliability = model.addVars(nodeSet, vtype=GRB.CONTINUOUS, name="nodeReliability")
    nodeUnreliability = model.addVars(nodeSet, vtype=GRB.CONTINUOUS, name="nodeUnreliability")
    logNodeReliability = model.addVars(nodeSet, vtype=GRB.CONTINUOUS, lb=-GRB.INFINITY, name="logNodeReliability")
    logNodeUnreliability = model.addVars(nodeSet, vtype=GRB.CONTINUOUS, lb=-GRB.INFINITY, name="logNodeUnreliability")
    logSubnetTotalReliability = model.addVars(subnetSet, vtype=GRB.CONTINUOUS, lb=-GRB.INFINITY, name="logSubnetTotalReliability")

    for u in nodeSet: # Definition of node reliability and unreliability
        model.addConstr( # Definition of nodeReliability[u]
            nodeReliability[u] == gp.quicksum(RELIABILITY_BY_NODE_TYPE[i] * x[u, i] for i in nodesTypeSet),
            name=f"NodeReliability_{u}"
        )
        model.addConstr(  # Definition of nodeUnreliability[u]
            nodeUnreliability[u] == 1 - gp.quicksum(RELIABILITY_BY_NODE_TYPE[i] * x[u, i] for i in nodesTypeSet),
            name=f"NodeUnreliability_{u}"
        )
        model.addGenConstrLog(  # Definition of logNodeReliability[u]
            nodeReliability[u], logNodeReliability[u],
            name=f"LogNodeReliability_{u}"
        )
        model.addGenConstrLog(  # Definition of logNodeUnreliability[u]
            nodeUnreliability[u], logNodeUnreliability[u],
            name=f"LogNodeUnreliability_{u}"
        )

    for j in subnetSet: # Definition of reliability per subnet
        if j == 0: # reliability of the series subnet
            model.addConstr( # Definition of series subnet reliability
                logSubnetTotalReliability[0] == gp.quicksum(y[u, 0] * logNodeReliability[u] for u in nodeSet),
                name=f"SeriesSubnetReliability_def_0"
            )
        else: # reliability of mesh subnets
            subnetUnreliability = model.addVar(vtype=GRB.CONTINUOUS, lb=-GRB.INFINITY, name=f"subnetUnreliability_{j}")
            expSubnetUnreliability = model.addVar(vtype=GRB.CONTINUOUS, lb=-GRB.INFINITY, name=f"expSubnetUnreliability_{j}")
            subnetReliability = model.addVar(vtype=GRB.CONTINUOUS, name=f"subnetReliability_{j}")
            logSubnetReliability = model.addVar(vtype=GRB.CONTINUOUS, lb=-GRB.INFINITY, name=f"logSubnetReliability_{j}")

            model.addConstr(  # Define subnetUnreliability
                subnetUnreliability == gp.quicksum(y[u, j] * logNodeUnreliability[u] for u in nodeSet),
                name=f"SubnetUnreliability_def_{j}"
            )
            model.addGenConstrExp(  # Define exp^K_j relationship
                subnetUnreliability, expSubnetUnreliability,
                name=f"expSubnetUnreliability_{j}"
            )
            model.addConstr( # Definition of subnetReliability
                subnetReliability == 1 - (activeSubnet[j]*expSubnetUnreliability),
                name=f"SubnetReliability_{j}"
            )
            model.addGenConstrLog(  # Define log(1-exp(K_j)) relationship
                subnetReliability, logSubnetReliability,
                name=f"LogSubnetReliability_{j}"
            )
            model.addConstr( # Definition of logSubnetTotalReliability[j]
                logSubnetTotalReliability[j] == logSubnetReliability,
                name=f"MeshSubnetReliability_def_{j}"
            )

    # Constraint for total network reliability
    totalReliability = model.addVar(vtype=GRB.CONTINUOUS, lb=-GRB.INFINITY, name="TotalReliability")

    model.addConstr(  # Definition of totalReliability
        totalReliability == gp.quicksum(logSubnetTotalReliability[j] for j in subnetSet),
        name="TotalReliability_def"
    )

    model.addConstr(  # Total reliability constraint
        totalReliability >= math.log(requiredReliability),
        name="TotalReliability_Constraint"
    )

    ################## END OF RELIABILITY ##################

    # Optimization
    model.optimize()

    # Check optimal solution
    if model.status == GRB.OPTIMAL:
        decision_variables = {var.varName: var.x for var in model.getVars()}
        return model.objVal, decision_variables, model
    else:
        print("No optimal solution found.")
        return None, None, model